version: '3.8'

services:
  openai-agent-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openai-agent-api
    ports:
      - "5000:5000"  # Host:Container
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5000
      - DEBUG=False
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      # Mount code files for development (optional - remove in production)
      - ./simple_agent.py:/app/simple_agent.py:ro
      - ./app.py:/app/app.py:ro
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge

